name: dem-comparison
channels:
  - conda-forge
dependencies:
  - rasterio=1.4.3
  - gdal=3.10.2
  - pip:
    - ipykernel
    - numpy==2.2.3
    - geopandas==1.0.1
    - rioxarray==0.18.2
    - aioboto3==14.1.0
    - pytest==8.3.5
    - coverage==7.6.12
    - requests==2.32.3
    - multiprocess==0.70.17
    - plotly==6.0.1
    - nbformat==5.10.4
    - matplotlib==3.10.1
    - black==25.1.0
    - pyyaml==6.0.2
    - gemgis==1.1.8
    - fiona==1.10.1
    - opencv-python-headless==4.11.0.86
    - statsmodels==0.14.4
    - git+https://github.com/GeoscienceAustralia/dem-handler.git